name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
    - name: Binary upload
      uses: actions/upload-artifact@v4
      with:
        name: ddptool-binary
        path: ddptool
        retention-days: 5
    
